export const mockCourses = [
  {
    id: "c1",
    slug: "algebra-1-mastery",
    title: "Algebra 1 Mastery",
    subject: "Algebra 1",
    gradeLevel: "8th-9th Grade",
    shortDescription: "Master every core Algebra 1 concept from equations to graphing.",
    description: "A complete Algebra 1 course covering linear equations, inequalities, systems of equations, functions, and graphing. Includes step-by-step PDF worksheets for every unit, practice problem sets, and answer keys.",
    previewDescription: "The first 2 lessons are free — get a feel for the format and teaching style before you buy.",
    priceCents: 4900,
    price: 49,
    totalLessons: 12,
    isPublished: true,
    lessons: [
      { id: "l1", title: "Introduction to Variables & Expressions", isFreePreview: true, order: 1, fileName: "01-variables-expressions.pdf" },
      { id: "l2", title: "Solving One-Step Equations", isFreePreview: true, order: 2, fileName: "02-one-step-equations.pdf" },
      { id: "l3", title: "Solving Two-Step Equations", isFreePreview: false, order: 3, fileName: "03-two-step-equations.pdf" },
      { id: "l4", title: "Multi-Step Equations & Word Problems", isFreePreview: false, order: 4, fileName: "04-multi-step-equations.pdf" },
      { id: "l5", title: "Inequalities & Graphing on Number Lines", isFreePreview: false, order: 5, fileName: "05-inequalities.pdf" },
      { id: "l6", title: "Linear Equations & Slope", isFreePreview: false, order: 6, fileName: "06-slope.pdf" },
      { id: "l7", title: "Graphing Linear Equations", isFreePreview: false, order: 7, fileName: "07-graphing.pdf" },
      { id: "l8", title: "Systems of Equations", isFreePreview: false, order: 8, fileName: "08-systems.pdf" },
      { id: "l9", title: "Exponents & Scientific Notation", isFreePreview: false, order: 9, fileName: "09-exponents.pdf" },
      { id: "l10", title: "Polynomials & Factoring", isFreePreview: false, order: 10, fileName: "10-polynomials.pdf" },
      { id: "l11", title: "Quadratic Equations", isFreePreview: false, order: 11, fileName: "11-quadratics.pdf" },
      { id: "l12", title: "Final Review & Practice Test", isFreePreview: false, order: 12, fileName: "12-final-review.pdf" },
    ],
  },
  {
    id: "c2",
    slug: "geometry-fundamentals",
    title: "Geometry Fundamentals",
    subject: "Geometry",
    gradeLevel: "9th-10th Grade",
    shortDescription: "Proofs, shapes, angles, and everything in between — made simple.",
    description: "A full Geometry course with PDF worksheets covering angle relationships, triangle congruence, similarity, circles, area and volume, coordinate geometry, and proofs. Perfect for students who struggled during the school year.",
    previewDescription: "Preview the first lesson free — see how we break down geometry proofs step by step.",
    priceCents: 4900,
    price: 49,
    totalLessons: 10,
    isPublished: true,
    lessons: [
      { id: "l13", title: "Points, Lines, Planes & Angle Basics", isFreePreview: true, order: 1, fileName: "01-angle-basics.pdf" },
      { id: "l14", title: "Parallel Lines & Transversals", isFreePreview: false, order: 2, fileName: "02-parallel-lines.pdf" },
      { id: "l15", title: "Triangle Congruence (SSS, SAS, ASA, AAS)", isFreePreview: false, order: 3, fileName: "03-congruence.pdf" },
      { id: "l16", title: "Triangle Similarity", isFreePreview: false, order: 4, fileName: "04-similarity.pdf" },
      { id: "l17", title: "Right Triangles & Pythagorean Theorem", isFreePreview: false, order: 5, fileName: "05-right-triangles.pdf" },
      { id: "l18", title: "Trigonometry Basics (SOH-CAH-TOA)", isFreePreview: false, order: 6, fileName: "06-trig-basics.pdf" },
      { id: "l19", title: "Circles — Arcs, Chords, Sectors", isFreePreview: false, order: 7, fileName: "07-circles.pdf" },
      { id: "l20", title: "Area & Perimeter", isFreePreview: false, order: 8, fileName: "08-area-perimeter.pdf" },
      { id: "l21", title: "Volume & Surface Area", isFreePreview: false, order: 9, fileName: "09-volume.pdf" },
      { id: "l22", title: "Coordinate Geometry & Final Review", isFreePreview: false, order: 10, fileName: "10-coordinate-geometry.pdf" },
    ],
  },
  {
    id: "c3",
    slug: "sat-math-prep",
    title: "SAT Math Prep Course",
    subject: "SAT Math",
    gradeLevel: "10th-12th Grade",
    shortDescription: "Strategy, practice, and confidence for the SAT Math sections.",
    description: "A focused SAT Math prep course covering Heart of Algebra, Problem Solving & Data Analysis, Passport to Advanced Math, and Additional Topics. Includes PDF strategy guides, timed practice sets, and full answer keys.",
    previewDescription: "The intro lesson is free — learn the SAT Math format and the biggest mistakes students make.",
    priceCents: 5900,
    price: 59,
    totalLessons: 8,
    isPublished: true,
    lessons: [
      { id: "l23", title: "SAT Math Overview & Test Strategy", isFreePreview: true, order: 1, fileName: "01-sat-overview.pdf" },
      { id: "l24", title: "Heart of Algebra — Linear Equations", isFreePreview: false, order: 2, fileName: "02-heart-of-algebra.pdf" },
      { id: "l25", title: "Problem Solving & Data Analysis", isFreePreview: false, order: 3, fileName: "03-data-analysis.pdf" },
      { id: "l26", title: "Passport to Advanced Math", isFreePreview: false, order: 4, fileName: "04-advanced-math.pdf" },
      { id: "l27", title: "Geometry & Trigonometry on the SAT", isFreePreview: false, order: 5, fileName: "05-geometry-trig.pdf" },
      { id: "l28", title: "Calculator vs No-Calculator Strategy", isFreePreview: false, order: 6, fileName: "06-calculator-strategy.pdf" },
      { id: "l29", title: "Timed Practice Test 1", isFreePreview: false, order: 7, fileName: "07-practice-test-1.pdf" },
      { id: "l30", title: "Timed Practice Test 2 + Answer Key", isFreePreview: false, order: 8, fileName: "08-practice-test-2.pdf" },
    ],
  },
];

export const mockBundle = {
  id: "b1",
  title: "Complete Math Prep Bundle",
  description: "All 3 courses — Algebra 1, Geometry, and SAT Math — at one discounted price. Everything your student needs from middle school through test prep.",
  priceCents: 11900,
  price: 119,
  originalPrice: 157,
  savings: 38,
  isPublished: true,
  courses: ["c1", "c2", "c3"],
};
