export const mockCourses = [
  {
    id: "c1",
    slug: "pre-algebra-mastery",
    title: "Pre-Algebra Mastery",
    subject: "Pre-Algebra",
    gradeLevel: "6th-8th Grade",
    shortDescription: "Build a strong math foundation with every core Pre-Algebra concept.",
    description: "A complete Pre-Algebra course covering number sense, fractions, decimals, ratios, proportions, integers, basic equations, and intro to functions. Includes step-by-step PDF worksheets, practice problem sets, and answer keys.",
    previewDescription: "The first 2 lessons are free — get a feel for the format and teaching style before you buy.",
    priceCents: 4900,
    price: 49,
    totalLessons: 10,
    isPublished: true,
    lessons: [
      { id: "l1", title: "Number Sense & Place Value", isFreePreview: true, order: 1, fileName: "01-number-sense.pdf" },
      { id: "l2", title: "Fractions, Decimals & Percents", isFreePreview: true, order: 2, fileName: "02-fractions-decimals.pdf" },
      { id: "l3", title: "Ratios & Proportions", isFreePreview: false, order: 3, fileName: "03-ratios-proportions.pdf" },
      { id: "l4", title: "Integers & Absolute Value", isFreePreview: false, order: 4, fileName: "04-integers.pdf" },
      { id: "l5", title: "Order of Operations (PEMDAS)", isFreePreview: false, order: 5, fileName: "05-order-of-operations.pdf" },
      { id: "l6", title: "Introduction to Variables & Expressions", isFreePreview: false, order: 6, fileName: "06-variables-expressions.pdf" },
      { id: "l7", title: "Solving One-Step Equations", isFreePreview: false, order: 7, fileName: "07-one-step-equations.pdf" },
      { id: "l8", title: "Solving Two-Step Equations", isFreePreview: false, order: 8, fileName: "08-two-step-equations.pdf" },
      { id: "l9", title: "Geometry Basics & Area/Perimeter", isFreePreview: false, order: 9, fileName: "09-geometry-basics.pdf" },
      { id: "l10", title: "Data, Graphs & Final Review", isFreePreview: false, order: 10, fileName: "10-data-graphs-review.pdf" },
    ],
  },
  {
    id: "c2",
    slug: "algebra-1-mastery",
    title: "Algebra 1 Mastery",
    subject: "Algebra 1",
    gradeLevel: "8th-9th Grade",
    shortDescription: "Master every core Algebra 1 concept from equations to graphing.",
    description: "A complete Algebra 1 course covering linear equations, inequalities, systems of equations, functions, and graphing. Includes step-by-step PDF worksheets for every unit, practice problem sets, and answer keys.",
    previewDescription: "The first 2 lessons are free — get a feel for the format and teaching style before you buy.",
    priceCents: 4900,
    price: 49,
    totalLessons: 12,
    isPublished: true,
    lessons: [
      { id: "l11", title: "Introduction to Variables & Expressions", isFreePreview: true, order: 1, fileName: "01-variables-expressions.pdf" },
      { id: "l12", title: "Solving One-Step Equations", isFreePreview: true, order: 2, fileName: "02-one-step-equations.pdf" },
      { id: "l13", title: "Solving Two-Step Equations", isFreePreview: false, order: 3, fileName: "03-two-step-equations.pdf" },
      { id: "l14", title: "Multi-Step Equations & Word Problems", isFreePreview: false, order: 4, fileName: "04-multi-step-equations.pdf" },
      { id: "l15", title: "Inequalities & Graphing on Number Lines", isFreePreview: false, order: 5, fileName: "05-inequalities.pdf" },
      { id: "l16", title: "Linear Equations & Slope", isFreePreview: false, order: 6, fileName: "06-slope.pdf" },
      { id: "l17", title: "Graphing Linear Equations", isFreePreview: false, order: 7, fileName: "07-graphing.pdf" },
      { id: "l18", title: "Systems of Equations", isFreePreview: false, order: 8, fileName: "08-systems.pdf" },
      { id: "l19", title: "Exponents & Scientific Notation", isFreePreview: false, order: 9, fileName: "09-exponents.pdf" },
      { id: "l20", title: "Polynomials & Factoring", isFreePreview: false, order: 10, fileName: "10-polynomials.pdf" },
      { id: "l21", title: "Quadratic Equations", isFreePreview: false, order: 11, fileName: "11-quadratics.pdf" },
      { id: "l22", title: "Final Review & Practice Test", isFreePreview: false, order: 12, fileName: "12-final-review.pdf" },
    ],
  },
];

export const mockBundle = {
  id: "b1",
  title: "Complete Math Bundle",
  description: "Both courses — Pre-Algebra and Algebra 1 — at one discounted price. The full progression from foundational math all the way through Algebra 1.",
  priceCents: 7900,
  price: 79,
  originalPrice: 98,
  savings: 19,
  isPublished: true,
  courses: ["c1", "c2"],
};
